quarkus.smallrye-openapi.info-title=Brand API
%dev.quarkus.smallrye-openapi.info-title=Example API (development)
quarkus.smallrye-openapi.open-api-version=3.0.4
%test.quarkus.smallrye-openapi.info-title=Brand API
quarkus.smallrye-openapi.info-description=API da disciplina de Web Services
quarkus.smallrye-openapi.info-terms-of-service=No terms
quarkus.smallrye-openapi.info-contact-email=victorfstedesco@senacsp.edu.br
quarkus.smallrye-openapi.info-contact-name=Senac TSI
quarkus.smallrye-openapi.info-contact-url=http://sp.senac.com.br
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.theme=flattop



# Database configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# CORS configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=X-Custom-Header,Content-Type,Authorization
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true
