quarkus.smallrye-openapi.info-title=Brand API
%dev.quarkus.smallrye-openapi.info-title=Example API (development)
quarkus.smallrye-openapi.open-api-version=3.0.4
%test.quarkus.smallrye-openapi.info-title=Example API (test)
quarkus.smallrye-openapi.info-description=Brand API
quarkus.smallrye-openapi.info-terms-of-service=No terms
quarkus.smallrye-openapi.info-contact-email=victor.fstedesco@senacsp.edu.br
quarkus.smallrye-openapi.info-contact-name=Brand API
quarkus.smallrye-openapi.info-contact-url=
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.theme=outline

# Database configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true